# Основные модули и пакеты
TOP_MODULE = top.sv
DUT_MODULE = vending_machine.sv
TB_PKG     = vm_pkg.sv


# Определения тестов и количества запусков (<имя_теста>:<количество_запусков>)
TESTS = write_registers_with_emergency_test:1 \
		check_write_test:0 \
		client_session_after_change_discount_test:0

include common.mk