import os
import sys
import yaml
from openpyxl import load_workbook

# =============================================================================
# Настройки путей и колонок
# =============================================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__)) 
# Поднимаемся на уровень выше и заходим в папку doc
XLSX_FILE = os.path.abspath(os.path.join(SCRIPT_DIR, "..", "doc", "testplan.xlsx"))
YAML_FILE = os.path.join(SCRIPT_DIR, "tests_suite.yaml")

# Список листов в Excel для парсинга
#TARGET_SHEETS = ["user_tests", "register_tests", "emergency_tests", "integration_tests", "errors_tests"]

START_ROW = 2                 # Строка, с которой начинаются тесты
COL_TEST_NAME = 2             # Столбец B (Имя теста)
COL_RUN_COUNT = 8             # Столбец H (Количество запусков)

def main():
    if not os.path.exists(XLSX_FILE):
        print(f"[ERROR] Excel file not found at: {XLSX_FILE}")
        sys.exit(1)

    print(f"--- Parsing Excel Testplan: {XLSX_FILE} ---")
    
    # Открываем Excel в режиме только для чтения
    wb = load_workbook(filename=XLSX_FILE, read_only=True, data_only=True)
    
    # Базовая структура YAML (все комментарии на английском)
    yaml_structure = {
        "defaults": {
            "count": 1,
            "verbosity": "UVM_LOW"
        },
        "suites": {}  # Группы тестов будут складываться сюда
    }

    total_active_tests = 0

    # Обходим каждый целевой лист
    for sheet_name in wb.sheetnames:
            
        sheet = wb[sheet_name]
        sheet_tests = {}
        
        # Идем по строкам текущего листа
        for row in range(START_ROW, sheet.max_row + 1):
            test_name = sheet.cell(row=row, column=COL_TEST_NAME).value
            run_count_val = sheet.cell(row=row, column=COL_RUN_COUNT).value

            if not test_name:
                continue

            test_name = str(test_name).strip()

            # Безопасное извлечение количества запусков (защита от типов линтера)
            try:
                if run_count_val is not None and isinstance(run_count_val, (int, float, str)):
                    run_count = int(float(run_count_val))
                else:
                    run_count = 0
            except ValueError:
                run_count = 0

            # Если тест активен, добавляем его в текущую группу
            if run_count > 0:
                total_active_tests += 1
                if run_count == 1:
                    sheet_tests[test_name] = None
                else:
                    sheet_tests[test_name] = {"count": run_count}
        
        # Если в группе есть хоть один активный тест, добавляем группу в YAML
        if sheet_tests:
            yaml_structure["suites"][sheet_name] = sheet_tests

    # Записываем результат в YAML (Файл создается в папке sim)
    with open(YAML_FILE, "w", encoding="utf-8") as f:
        f.write("# =============================================================================\n")
        f.write("# GENERATED AUTOMATICALLY FROM THE TESTPLAN. DO NOT EDIT THIS FILE MANUALLY!\n")
        f.write("# =============================================================================\n\n")
        
        yaml.dump(yaml_structure, f, default_flow_style=False, sort_keys=False)

    print(f"[SUCCESS] Generated '{YAML_FILE}'. Total active tests added: {total_active_tests}")

if __name__ == "__main__":
    main()