`include "../user_tests/user_base_test.sv"

`include "../user_tests/simple_test.sv"
`include "../user_tests/one_coin_test.sv"
`include "../user_tests/few_coin_test.sv"
`include "../user_tests/dollars_test.sv"
`include "../user_tests/euros_test.sv"
`include "../user_tests/random_client_without_change_test.sv"
`include "../user_tests/client_session_without_errors_test.sv"
`include "../user_tests/lots_of_purchases_test.sv"

`include "../user_tests/coin_timeout_refund_test.sv"
`include "../user_tests/confirm_timeout_refund_test.sv"
`include "../user_tests/invalid_client_id_test.sv"
`include "../user_tests/invalid_coin_denomination_test.sv"
`include "../user_tests/insufficient_funds_test.sv"