import os
import sys
import yaml
from openpyxl import load_workbook

class TestplanParser:
    def __init__(self, xlsx_path=None, yaml_path=None):
        # Находимся в sim/infra/
        self.infra_dir = os.path.dirname(os.path.abspath(__file__))
        # Поднимаемся на уровень выше — в корень sim/
        self.sim_dir = os.path.abspath(os.path.join(self.infra_dir, ".."))
        
        # Корректируем пути: до doc поднимаемся на два уровня вверх (из infra/ через sim/)
        self.xlsx_file = xlsx_path or os.path.abspath(os.path.join(self.sim_dir, "..", "doc", "testplan.xlsx"))
        # Файл конфигурации сохраняем в корне sim/
        self.yaml_file = yaml_path or os.path.join(self.sim_dir, "tests_suite.yaml")

        
        self.start_row = 2
        self.col_test_name = 2
        self.col_run_count = 8

    def is_sync_needed(self) -> bool:
        """Проверяет, новее ли Excel-файл, чем сгенерированный YAML"""
        if not os.path.exists(self.yaml_file):
            return True  # YAML нет, синхронизация обязательна
        if not os.path.exists(self.xlsx_file):
            return False # Excel нет (например, в CI), работаем по существующему YAML
            
        # Сравниваем время последнего изменения файлов
        return os.path.getmtime(self.xlsx_file) > os.path.getmtime(self.yaml_file)

    def sync(self) -> bool:
        """Парсит Excel и обновляет YAML-конфигурацию"""
        if not os.path.exists(self.xlsx_file):
            print(f"[WARNING] Excel testplan not found at {self.xlsx_file}. Skipping sync.")
            return False

        print(f"--- Syncing Testplan: {os.path.basename(self.xlsx_file)} -> {os.path.basename(self.yaml_file)} ---")
        
        try:
            # Открываем Excel в режиме только для чтения
            wb = load_workbook(filename=self.xlsx_file, read_only=True, data_only=True)
            
            yaml_structure = {
                "defaults": {"count": 1, "verbosity": "UVM_LOW"},
                "suites": {}
            }
            total_active_tests = 0

            for sheet_name in wb.sheetnames:
                sheet = wb[sheet_name]
                sheet_tests = {}
                
                # Защита: openpyxl в read_only режиме иногда не знает max_row, 
                # поэтому итерируемся аккуратно или используем итератор строк
                for row in range(self.start_row, sheet.max_row + 1 if sheet.max_row else 1000):
                    test_name_val = sheet.cell(row=row, column=self.col_test_name).value
                    run_count_val = sheet.cell(row=row, column=self.col_run_count).value

                    if not test_name_val:
                        continue

                    test_name = str(test_name_val).strip()
                    try:
                        if run_count_val is not None and isinstance(run_count_val, (int, float, str)):
                            run_count = int(float(run_count_val))
                        else:
                            run_count = 0
                    except ValueError:
                        run_count = 0
                        

                    if run_count > 0:
                        total_active_tests += 1
                        if run_count == 1:
                            sheet_tests[test_name] = None
                        else:
                            sheet_tests[test_name] = {"count": run_count}
                
                if sheet_tests:
                    yaml_structure["suites"][sheet_name] = sheet_tests

            # Записываем результат в YAML
            with open(self.yaml_file, "w", encoding="utf-8") as f:
                f.write("# =============================================================================\n")
                f.write("# GENERATED AUTOMATICALLY FROM THE TESTPLAN. DO NOT EDIT THIS FILE MANUALLY!\n")
                f.write("# =============================================================================\n\n")
                yaml.dump(yaml_structure, f, default_flow_style=False, sort_keys=False)

            print(f"[SUCCESS] Sync complete. Active tests: {total_active_tests}")
            return True

        except PermissionError:
            print(f"[WARNING] Cannot read {os.path.basename(self.xlsx_file)}. It might be open in Excel. Using existing YAML config.")
            return False
        except Exception as e:
            print(f"[ERROR] Testplan sync failed: {e}")
            return False